version: '3'

vars:
  BINARY_NAME: @ign-var:PROJECT_NAME@

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  build:
    desc: Build the binary
    cmds:
      - cargo build

  build-release:
    desc: Build the release binary
    cmds:
      - cargo build --release

  run:
    desc: Run the application
    cmds:
      - cargo run

  test:
    desc: Run tests with nextest
    cmds:
      - cargo nextest run

  test-verbose:
    desc: Run tests with verbose output
    cmds:
      - cargo nextest run --no-capture

  test-cargo:
    desc: Run tests with cargo test
    cmds:
      - cargo test

  check:
    desc: Run cargo check
    cmds:
      - cargo check

  clippy:
    desc: Run clippy linter
    cmds:
      - cargo clippy --all-targets -- -D warnings

  fmt:
    desc: Format code
    cmds:
      - cargo fmt

  fmt-check:
    desc: Check code formatting
    cmds:
      - cargo fmt -- --check

  lint:
    desc: Run all lints (fmt check + clippy)
    cmds:
      - task: fmt-check
      - task: clippy

  clean:
    desc: Clean build artifacts
    cmds:
      - cargo clean

  doc:
    desc: Generate documentation
    cmds:
      - cargo doc --no-deps

  doc-open:
    desc: Generate and open documentation
    cmds:
      - cargo doc --no-deps --open

  audit:
    desc: Run security audit
    cmds:
      - cargo audit

  ci:
    desc: Run all CI checks
    cmds:
      - task: fmt-check
      - task: clippy
      - task: test
      - task: build
