version: '3'

vars:
  TEMPLATES_DIR: '{{.ROOT_DIR}}'

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  template-list:
    desc: List all available ign templates
    cmds:
      - |
        echo "Available templates in {{.TEMPLATES_DIR}}:"
        for json in {{.TEMPLATES_DIR}}/*/ign-template.json; do
          if [ -f "$json" ]; then
            dir=$(dirname "$json")
            name=$(basename "$dir")
            echo "  - $name"
          fi
        done

  template-update:
    desc: "Update a specific template (usage: task template-update TEMPLATE=go-v1)"
    requires:
      vars: [TEMPLATE]
    cmds:
      - |
        template_dir="{{.TEMPLATES_DIR}}/{{.TEMPLATE}}"
        if [ ! -f "$template_dir/ign-template.json" ]; then
          echo "Error: Template '{{.TEMPLATE}}' not found (missing ign-template.json)"
          exit 1
        fi
        echo "Updating template: {{.TEMPLATE}}"
        ign template update "$template_dir"

  template-update-all:
    desc: Update all ign templates
    cmds:
      - |
        echo "Updating all templates..."
        for json in {{.TEMPLATES_DIR}}/*/ign-template.json; do
          if [ -f "$json" ]; then
            dir=$(dirname "$json")
            name=$(basename "$dir")
            echo "========================================"
            echo "Template: $name"
            echo "========================================"
            ign template update "$dir"
            echo ""
          fi
        done
        echo "All templates updated."

  template-check:
    desc: "Check a specific template for syntax errors (usage: task template-check TEMPLATE=go-v1)"
    requires:
      vars: [TEMPLATE]
    cmds:
      - |
        template_dir="{{.TEMPLATES_DIR}}/{{.TEMPLATE}}"
        if [ ! -f "$template_dir/ign-template.json" ]; then
          echo "Error: Template '{{.TEMPLATE}}' not found (missing ign-template.json)"
          exit 1
        fi
        echo "Checking template: {{.TEMPLATE}}"
        ign template check "$template_dir" -r -v

  template-check-all:
    desc: Check all ign templates for syntax errors
    cmds:
      - |
        echo "Checking all templates..."
        for json in {{.TEMPLATES_DIR}}/*/ign-template.json; do
          if [ -f "$json" ]; then
            dir=$(dirname "$json")
            name=$(basename "$dir")
            echo "========================================"
            echo "Template: $name"
            echo "========================================"
            ign template check "$dir" -r -v
            echo ""
          fi
        done
        echo "All templates checked."
