version: '3'

vars:
  PROJECT_NAME: @ign-var:PROJECT_NAME@

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  install:
    desc: Install dependencies
    cmds:
      - bun install

  dev:
    desc: Run in development mode with watch
    cmds:
      - bun run dev

  build:
    desc: Build the project
    cmds:
      - bun run build

  start:
    desc: Run the application
    cmds:
      - bun run start

  test:
    desc: Run tests
    cmds:
      - bun test

  test-watch:
    desc: Run tests in watch mode
    cmds:
      - bun test --watch

  test-verbose:
    desc: Run tests with verbose output
    cmds:
      - bun test --verbose

  typecheck:
    desc: Run TypeScript type checking
    cmds:
      - bun run typecheck

  fmt:
    desc: Format code with prettier
    cmds:
      - bun run format

  fmt-check:
    desc: Check code formatting
    cmds:
      - bun run format:check

  lint:
    desc: Run all lints (format check + typecheck)
    cmds:
      - task: fmt-check
      - task: typecheck

  clean:
    desc: Clean build artifacts
    cmds:
      - bun run clean

  ci:
    desc: Run all CI checks
    cmds:
      - task: fmt-check
      - task: typecheck
      - task: test
      - task: build
